### ISSUE TITLE
各种crash

### ISSUE THREAD

**Issue by GvcZhang** [18601949127/DiDiCallCar#5]
各种crash

**Comment by xumingyi** [comment]
我也是各种crash，这么多星的app，感觉不应该出这类问题，哪里出错了呢？ 
  java.lang.IllegalArgumentException: BDMapSDKException: option or keyword or city can not be null
        at com.baidu.mapapi.search.sug.SuggestionSearch.requestSuggestion(Unknown Source:25)
        at com.ftd.didicar.TabFragment.TabFragment0$1.onTextChanged(TabFragment0.java:230)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9389)
        at android.widget.TextView.handleTextChanged(TextView.java:9476)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12105)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)

**Comment by 18601949127** [comment]
这个错误没有人反应过的，你再看看。我在手机上跑通了，才整体发到Git上面去的



---原始邮件---
发件人: "FTD_2014"<notifications@github.com&gt;
发送时间: 2019年12月25日(周三) 下午5:16
收件人: "18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [18601949127/DiDiCallCar] 各种crash (#5)



我也是各种crash，这么多星的app，感觉不应该出这类问题，哪里出错了呢？
 java.lang.IllegalArgumentException: BDMapSDKException: option or keyword or city can not be null
 at com.baidu.mapapi.search.sug.SuggestionSearch.requestSuggestion(Unknown Source:25)
 at com.ftd.didicar.TabFragment.TabFragment0$1.onTextChanged(TabFragment0.java:230)
 at android.widget.TextView.sendOnTextChanged(TextView.java:9389)
 at android.widget.TextView.handleTextChanged(TextView.java:9476)
 at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12105)
 at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)

**Comment by xumingyi** [comment]
> 这个错误没有人反应过的，你再看看。我在手机上跑通了，才整体发到Git上面去的
> […](#)
> ---原始邮件--- 发件人: "FTD_2014"<notifications@github.com&gt; 发送时间: 2019年12月25日(周三) 下午5:16 收件人: "18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [18601949127/DiDiCallCar] 各种crash (#5) 我也是各种crash，这么多星的app，感觉不应该出这类问题，哪里出错了呢？ java.lang.IllegalArgumentException: BDMapSDKException: option or keyword or city can not be null at com.baidu.mapapi.search.sug.SuggestionSearch.requestSuggestion(Unknown Source:25) at com.ftd.didicar.TabFragment.TabFragment0$1.onTextChanged(TabFragment0.java:230) at android.widget.TextView.sendOnTextChanged(TextView.java:9389) at android.widget.TextView.handleTextChanged(TextView.java:9476) at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12105) at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我也是编译通过后加上了自己的包名和key发现定位不好用，而且会crash(红米9.0设备和oppo 7.0上都是一样的)，因为导航确实是快硬骨头，所以才想学习下，能够先给我发一个你那边编译好的apk包，我下载试试呢

**Comment by xumingyi** [comment]
我是用包名和key在百度地图上是能够定位的

**Comment by xumingyi** [comment]
我是用包名和key在百度地图的demo上是能够定位的，我想也不应该出这种问题，可以加一下微信或者qq交流下嘛？

**Comment by 18601949127** [comment]
导航算什么硬骨头，别人都做好了的东西


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FTD_2014"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 中午1:43
收件人:&nbsp;"18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com&gt;;
抄送:&nbsp;"谭妥"<1991201740@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [18601949127/DiDiCallCar] 各种crash (#5)



 
这个错误没有人反应过的，你再看看。我在手机上跑通了，才整体发到Git上面去的
 …
 ---原始邮件--- 发件人: "FTD_2014"<notifications@github.com&gt; 发送时间: 2019年12月25日(周三) 下午5:16 收件人: "18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [18601949127/DiDiCallCar] 各种crash (#5) 我也是各种crash，这么多星的app，感觉不应该出这类问题，哪里出错了呢？ java.lang.IllegalArgumentException: BDMapSDKException: option or keyword or city can not be null at com.baidu.mapapi.search.sug.SuggestionSearch.requestSuggestion(Unknown Source:25) at com.ftd.didicar.TabFragment.TabFragment0$1.onTextChanged(TabFragment0.java:230) at android.widget.TextView.sendOnTextChanged(TextView.java:9389) at android.widget.TextView.handleTextChanged(TextView.java:9476) at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12105) at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好，我也是编译通过后加上了自己的包名和key发现定位不好用，而且会crash(红米9.0设备和oppo 7.0上都是一样的)，因为导航确实是快硬骨头，所以才想学习下，能够先给我发一个你那边编译好的apk包，我下载试试呢

**Comment by xumingyi** [comment]
> 导航算什么硬骨头，别人都做好了的东西
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"FTD_2014"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月26日(星期四) 中午1:43 收件人:&nbsp;"18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com&gt;; 抄送:&nbsp;"谭妥"<1991201740@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [18601949127/DiDiCallCar] 各种crash (#5) 这个错误没有人反应过的，你再看看。我在手机上跑通了，才整体发到Git上面去的 … ---原始邮件--- 发件人: "FTD_2014"<notifications@github.com&gt; 发送时间: 2019年12月25日(周三) 下午5:16 收件人: "18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [18601949127/DiDiCallCar] 各种crash (#5) 我也是各种crash，这么多星的app，感觉不应该出这类问题，哪里出错了呢？ java.lang.IllegalArgumentException: BDMapSDKException: option or keyword or city can not be null at com.baidu.mapapi.search.sug.SuggestionSearch.requestSuggestion(Unknown Source:25) at com.ftd.didicar.TabFragment.TabFragment0$1.onTextChanged(TabFragment0.java:230) at android.widget.TextView.sendOnTextChanged(TextView.java:9389) at android.widget.TextView.handleTextChanged(TextView.java:9476) at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12105) at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，我也是编译通过后加上了自己的包名和key发现定位不好用，而且会crash(红米9.0设备和oppo 7.0上都是一样的)，因为导航确实是快硬骨头，所以才想学习下，能够先给我发一个你那边编译好的apk包，我下载试试呢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

哈哈，导航是一个完整的业务，没做过导航。
